services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_payment_api
    restart: unless-stopped
    ports:
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - school_net

  db:
    image: postgres:16-alpine
    container_name: school_payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - school_net

volumes:
  postgres_data:
    driver: local

networks:
  school_net:
    driver: bridge