(BRANCH_NAME, BRANCH_FEE, BRANCH_MFO, BRANCH_ACC, BRANCH_MERCHANT) = range(5)

(
    STUDENT_BRANCH, STUDENT_PARENT, STUDENT_FULLNAME,
    STUDENT_GROUP_NAME, STUDENT_PHONE, STUDENT_DISCOUNT
) = range(5, 11)

(DELETE_STUDENT_ACCOUNT_ID) = range(11, 12)

(DELETE_BRANCH_SELECT, DELETE_BRANCH_CONFIRM) = range(12, 14)

PROCESSING_EXCEL_FILE = range(14, 15)

(CHANGE_STATUS_ACCOUNT_ID, CONFIRM_STATUS_CHANGE) = range(15, 17)