(BRANCH_NAME, BRANCH_FEE, BRANCH_MFO, BRANCH_ACC, BRANCH_MERCHANT, BRANCH_TOPIC_ID) = range(6)

(
    STUDENT_BRANCH, STUDENT_PARENT, STUDENT_FULLNAME,
    STUDENT_GROUP_NAME, STUDENT_PHONE, STUDENT_DISCOUNT
) = range(6, 12)

(DELETE_STUDENT_ACCOUNT_ID) = range(12, 13)

(DELETE_BRANCH_SELECT, DELETE_BRANCH_CONFIRM) = range(13, 15)

PROCESSING_EXCEL_FILE = range(15, 16)

(CHANGE_STATUS_ACCOUNT_ID, CONFIRM_STATUS_CHANGE) = range(16, 18)