// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: bot_admin.proto

package bot_admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotAdminService_NotifyPaymentSuccess_FullMethodName = "/bot_admin.BotAdminService/NotifyPaymentSuccess"
)

// BotAdminServiceClient is the client API for BotAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotAdminServiceClient interface {
	NotifyPaymentSuccess(ctx context.Context, in *NotifyPaymentSuccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type botAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotAdminServiceClient(cc grpc.ClientConnInterface) BotAdminServiceClient {
	return &botAdminServiceClient{cc}
}

func (c *botAdminServiceClient) NotifyPaymentSuccess(ctx context.Context, in *NotifyPaymentSuccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BotAdminService_NotifyPaymentSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotAdminServiceServer is the server API for BotAdminService service.
// All implementations must embed UnimplementedBotAdminServiceServer
// for forward compatibility.
type BotAdminServiceServer interface {
	NotifyPaymentSuccess(context.Context, *NotifyPaymentSuccessRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBotAdminServiceServer()
}

// UnimplementedBotAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotAdminServiceServer struct{}

func (UnimplementedBotAdminServiceServer) NotifyPaymentSuccess(context.Context, *NotifyPaymentSuccessRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaymentSuccess not implemented")
}
func (UnimplementedBotAdminServiceServer) mustEmbedUnimplementedBotAdminServiceServer() {}
func (UnimplementedBotAdminServiceServer) testEmbeddedByValue()                         {}

// UnsafeBotAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotAdminServiceServer will
// result in compilation errors.
type UnsafeBotAdminServiceServer interface {
	mustEmbedUnimplementedBotAdminServiceServer()
}

func RegisterBotAdminServiceServer(s grpc.ServiceRegistrar, srv BotAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedBotAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotAdminService_ServiceDesc, srv)
}

func _BotAdminService_NotifyPaymentSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPaymentSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAdminServiceServer).NotifyPaymentSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAdminService_NotifyPaymentSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAdminServiceServer).NotifyPaymentSuccess(ctx, req.(*NotifyPaymentSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotAdminService_ServiceDesc is the grpc.ServiceDesc for BotAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bot_admin.BotAdminService",
	HandlerType: (*BotAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyPaymentSuccess",
			Handler:    _BotAdminService_NotifyPaymentSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot_admin.proto",
}
