// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: bot_admin.proto

package bot_admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyPaymentSuccessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StudentName    string                 `protobuf:"bytes,1,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	BranchName     string                 `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	GroupName      string                 `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentTime    string                 `protobuf:"bytes,5,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time,omitempty"`
	AccountId      string                 `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ContractNumber string                 `protobuf:"bytes,7,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	TopicId        int64                  `protobuf:"varint,8,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // YANGI: Xabar yuboriladigan Topic ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyPaymentSuccessRequest) Reset() {
	*x = NotifyPaymentSuccessRequest{}
	mi := &file_bot_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentSuccessRequest) ProtoMessage() {}

func (x *NotifyPaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_bot_admin_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyPaymentSuccessRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NotifyPaymentSuccessRequest) GetPaymentTime() string {
	if x != nil {
		return x.PaymentTime
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *NotifyPaymentSuccessRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

var File_bot_admin_proto protoreflect.FileDescriptor

const file_bot_admin_proto_rawDesc = "" +
	"\n" +
	"\x0fbot_admin.proto\x12\tbot_admin\x1a\x1bgoogle/protobuf/empty.proto\"\x9e\x02\n" +
	"\x1bNotifyPaymentSuccessRequest\x12!\n" +
	"\fstudent_name\x18\x01 \x01(\tR\vstudentName\x12\x1f\n" +
	"\vbranch_name\x18\x02 \x01(\tR\n" +
	"branchName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12!\n" +
	"\fpayment_time\x18\x05 \x01(\tR\vpaymentTime\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tR\taccountId\x12'\n" +
	"\x0fcontract_number\x18\a \x01(\tR\x0econtractNumber\x12\x19\n" +
	"\btopic_id\x18\b \x01(\x03R\atopicId2i\n" +
	"\x0fBotAdminService\x12V\n" +
	"\x14NotifyPaymentSuccess\x12&.bot_admin.NotifyPaymentSuccessRequest\x1a\x16.google.protobuf.EmptyB\x1aZ\x18payme/genproto/bot_adminb\x06proto3"

var (
	file_bot_admin_proto_rawDescOnce sync.Once
	file_bot_admin_proto_rawDescData []byte
)

func file_bot_admin_proto_rawDescGZIP() []byte {
	file_bot_admin_proto_rawDescOnce.Do(func() {
		file_bot_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_admin_proto_rawDesc), len(file_bot_admin_proto_rawDesc)))
	})
	return file_bot_admin_proto_rawDescData
}

var file_bot_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bot_admin_proto_goTypes = []any{
	(*NotifyPaymentSuccessRequest)(nil), // 0: bot_admin.NotifyPaymentSuccessRequest
	(*emptypb.Empty)(nil),               // 1: google.protobuf.Empty
}
var file_bot_admin_proto_depIdxs = []int32{
	0, // 0: bot_admin.BotAdminService.NotifyPaymentSuccess:input_type -> bot_admin.NotifyPaymentSuccessRequest
	1, // 1: bot_admin.BotAdminService.NotifyPaymentSuccess:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bot_admin_proto_init() }
func file_bot_admin_proto_init() {
	if File_bot_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_admin_proto_rawDesc), len(file_bot_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_admin_proto_goTypes,
		DependencyIndexes: file_bot_admin_proto_depIdxs,
		MessageInfos:      file_bot_admin_proto_msgTypes,
	}.Build()
	File_bot_admin_proto = out.File
	file_bot_admin_proto_goTypes = nil
	file_bot_admin_proto_depIdxs = nil
}
