// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MonthlyFee    int64                  `protobuf:"varint,3,opt,name=monthly_fee,json=monthlyFee,proto3" json:"monthly_fee,omitempty"`
	MfoCode       string                 `protobuf:"bytes,4,opt,name=mfo_code,json=mfoCode,proto3" json:"mfo_code,omitempty"`
	AccountNumber string                 `protobuf:"bytes,5,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	MerchantId    string                 `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,7,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // YANGI: Telegram Topic ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Branch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetMonthlyFee() int64 {
	if x != nil {
		return x.MonthlyFee
	}
	return 0
}

func (x *Branch) GetMfoCode() string {
	if x != nil {
		return x.MfoCode
	}
	return ""
}

func (x *Branch) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Branch) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Branch) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type Student struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BranchId        string                 `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	ParentName      string                 `protobuf:"bytes,4,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	DiscountPercent float64                `protobuf:"fixed64,5,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	Balance         int64                  `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	FullName        string                 `protobuf:"bytes,7,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	GroupName       string                 `protobuf:"bytes,8,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Phone           string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	ContractNumber  string                 `protobuf:"bytes,10,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	Status          bool                   `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Student) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *Student) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *Student) GetDiscountPercent() float64 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *Student) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Student) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Student) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Student) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Student) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *Student) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByIdRequest) Reset() {
	*x = ByIdRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByIdRequest) ProtoMessage() {}

func (x *ByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByIdRequest.ProtoReflect.Descriptor instead.
func (*ByIdRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ByAccountIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByAccountIdRequest) Reset() {
	*x = ByAccountIdRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByAccountIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByAccountIdRequest) ProtoMessage() {}

func (x *ByAccountIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByAccountIdRequest.ProtoReflect.Descriptor instead.
func (*ByAccountIdRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ByAccountIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MonthlyFee    int64                  `protobuf:"varint,2,opt,name=monthly_fee,json=monthlyFee,proto3" json:"monthly_fee,omitempty"`
	MfoCode       string                 `protobuf:"bytes,3,opt,name=mfo_code,json=mfoCode,proto3" json:"mfo_code,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	MerchantId    string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,6,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // YANGI: Telegram Topic ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetMonthlyFee() int64 {
	if x != nil {
		return x.MonthlyFee
	}
	return 0
}

func (x *CreateBranchRequest) GetMfoCode() string {
	if x != nil {
		return x.MfoCode
	}
	return ""
}

func (x *CreateBranchRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateBranchRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateBranchRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type CreateStudentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BranchId        string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	ParentName      string                 `protobuf:"bytes,3,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	DiscountPercent float64                `protobuf:"fixed64,4,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	FullName        string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	GroupName       string                 `protobuf:"bytes,6,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Phone           string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	ContractNumber  string                 `protobuf:"bytes,8,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStudentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateStudentRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *CreateStudentRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *CreateStudentRequest) GetDiscountPercent() float64 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *CreateStudentRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateStudentRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateStudentRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateStudentRequest) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

type ListStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsResponse) Reset() {
	*x = ListStudentsResponse{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsResponse) ProtoMessage() {}

func (x *ListStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *ListStudentsResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type CreateStudentsBatchRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Students      []*CreateStudentRequest `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentsBatchRequest) Reset() {
	*x = CreateStudentsBatchRequest{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentsBatchRequest) ProtoMessage() {}

func (x *CreateStudentsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentsBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentsBatchRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStudentsBatchRequest) GetStudents() []*CreateStudentRequest {
	if x != nil {
		return x.Students
	}
	return nil
}

type CreateStudentsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentsBatchResponse) Reset() {
	*x = CreateStudentsBatchResponse{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentsBatchResponse) ProtoMessage() {}

func (x *CreateStudentsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentsBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentsBatchResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *CreateStudentsBatchResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type UpdateStudentsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentsBatchRequest) Reset() {
	*x = UpdateStudentsBatchRequest{}
	mi := &file_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentsBatchRequest) ProtoMessage() {}

func (x *UpdateStudentsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentsBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentsBatchRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStudentsBatchRequest) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type DeleteStudentsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentsBatchRequest) Reset() {
	*x = DeleteStudentsBatchRequest{}
	mi := &file_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentsBatchRequest) ProtoMessage() {}

func (x *DeleteStudentsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentsBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentsBatchRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteStudentsBatchRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{13}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckPerformTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPerformTransactionRequest) Reset() {
	*x = CheckPerformTransactionRequest{}
	mi := &file_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPerformTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPerformTransactionRequest) ProtoMessage() {}

func (x *CheckPerformTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPerformTransactionRequest.ProtoReflect.Descriptor instead.
func (*CheckPerformTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPerformTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CheckPerformTransactionRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type StudentAdditionalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ParentName    string                 `protobuf:"bytes,2,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	BranchName    string                 `protobuf:"bytes,3,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupNumber   string                 `protobuf:"bytes,5,opt,name=group_number,json=groupNumber,proto3" json:"group_number,omitempty"`
	AmountToPay   int64                  `protobuf:"varint,6,opt,name=amount_to_pay,json=amountToPay,proto3" json:"amount_to_pay,omitempty"`
	MfoCode       string                 `protobuf:"bytes,7,opt,name=mfo_code,json=mfoCode,proto3" json:"mfo_code,omitempty"`
	AccountNumber string                 `protobuf:"bytes,8,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentAdditionalInfo) Reset() {
	*x = StudentAdditionalInfo{}
	mi := &file_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentAdditionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentAdditionalInfo) ProtoMessage() {}

func (x *StudentAdditionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentAdditionalInfo.ProtoReflect.Descriptor instead.
func (*StudentAdditionalInfo) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{15}
}

func (x *StudentAdditionalInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *StudentAdditionalInfo) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *StudentAdditionalInfo) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *StudentAdditionalInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *StudentAdditionalInfo) GetGroupNumber() string {
	if x != nil {
		return x.GroupNumber
	}
	return ""
}

func (x *StudentAdditionalInfo) GetAmountToPay() int64 {
	if x != nil {
		return x.AmountToPay
	}
	return 0
}

func (x *StudentAdditionalInfo) GetMfoCode() string {
	if x != nil {
		return x.MfoCode
	}
	return ""
}

func (x *StudentAdditionalInfo) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CheckPerformTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Additional    *StudentAdditionalInfo `protobuf:"bytes,2,opt,name=additional,proto3" json:"additional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPerformTransactionResponse) Reset() {
	*x = CheckPerformTransactionResponse{}
	mi := &file_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPerformTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPerformTransactionResponse) ProtoMessage() {}

func (x *CheckPerformTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPerformTransactionResponse.ProtoReflect.Descriptor instead.
func (*CheckPerformTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{16}
}

func (x *CheckPerformTransactionResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *CheckPerformTransactionResponse) GetAdditional() *StudentAdditionalInfo {
	if x != nil {
		return x.Additional
	}
	return nil
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Account       *Account               `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTransactionRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type Receiver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	mi := &file_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{18}
}

func (x *Receiver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Receiver) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateTime    int64                  `protobuf:"varint,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Transaction   string                 `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Receivers     []*Receiver            `protobuf:"bytes,4,rep,name=receivers,proto3" json:"receivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{19}
}

func (x *CreateTransactionResponse) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CreateTransactionResponse) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *CreateTransactionResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CreateTransactionResponse) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_payment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{20}
}

func (x *TransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PerformTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   string                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	PerformTime   int64                  `protobuf:"varint,2,opt,name=perform_time,json=performTime,proto3" json:"perform_time,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformTransactionResponse) Reset() {
	*x = PerformTransactionResponse{}
	mi := &file_payment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformTransactionResponse) ProtoMessage() {}

func (x *PerformTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformTransactionResponse.ProtoReflect.Descriptor instead.
func (*PerformTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{21}
}

func (x *PerformTransactionResponse) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *PerformTransactionResponse) GetPerformTime() int64 {
	if x != nil {
		return x.PerformTime
	}
	return 0
}

func (x *PerformTransactionResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type CancelTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        int32                  `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionRequest) Reset() {
	*x = CancelTransactionRequest{}
	mi := &file_payment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionRequest) ProtoMessage() {}

func (x *CancelTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionRequest.ProtoReflect.Descriptor instead.
func (*CancelTransactionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{22}
}

func (x *CancelTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelTransactionRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type CancelTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   string                 `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	CancelTime    int64                  `protobuf:"varint,2,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionResponse) Reset() {
	*x = CancelTransactionResponse{}
	mi := &file_payment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionResponse) ProtoMessage() {}

func (x *CancelTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionResponse.ProtoReflect.Descriptor instead.
func (*CancelTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{23}
}

func (x *CancelTransactionResponse) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *CancelTransactionResponse) GetCancelTime() int64 {
	if x != nil {
		return x.CancelTime
	}
	return 0
}

func (x *CancelTransactionResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type CheckTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateTime    int64                  `protobuf:"varint,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PerformTime   int64                  `protobuf:"varint,2,opt,name=perform_time,json=performTime,proto3" json:"perform_time,omitempty"`
	CancelTime    int64                  `protobuf:"varint,3,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	Transaction   string                 `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	State         int32                  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Reason        *int32                 `protobuf:"varint,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTransactionResponse) Reset() {
	*x = CheckTransactionResponse{}
	mi := &file_payment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTransactionResponse) ProtoMessage() {}

func (x *CheckTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTransactionResponse.ProtoReflect.Descriptor instead.
func (*CheckTransactionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{24}
}

func (x *CheckTransactionResponse) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CheckTransactionResponse) GetPerformTime() int64 {
	if x != nil {
		return x.PerformTime
	}
	return 0
}

func (x *CheckTransactionResponse) GetCancelTime() int64 {
	if x != nil {
		return x.CancelTime
	}
	return 0
}

func (x *CheckTransactionResponse) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *CheckTransactionResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CheckTransactionResponse) GetReason() int32 {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return 0
}

type GetStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementRequest) Reset() {
	*x = GetStatementRequest{}
	mi := &file_payment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementRequest) ProtoMessage() {}

func (x *GetStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementRequest.ProtoReflect.Descriptor instead.
func (*GetStatementRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{25}
}

func (x *GetStatementRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GetStatementRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type StatementTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Account       *Account               `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	PerformTime   int64                  `protobuf:"varint,6,opt,name=perform_time,json=performTime,proto3" json:"perform_time,omitempty"`
	CancelTime    int64                  `protobuf:"varint,7,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	Transaction   string                 `protobuf:"bytes,8,opt,name=transaction,proto3" json:"transaction,omitempty"`
	State         int32                  `protobuf:"varint,9,opt,name=state,proto3" json:"state,omitempty"`
	Reason        *int32                 `protobuf:"varint,10,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	Receivers     []*Receiver            `protobuf:"bytes,11,rep,name=receivers,proto3" json:"receivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatementTransaction) Reset() {
	*x = StatementTransaction{}
	mi := &file_payment_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementTransaction) ProtoMessage() {}

func (x *StatementTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementTransaction.ProtoReflect.Descriptor instead.
func (*StatementTransaction) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{26}
}

func (x *StatementTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatementTransaction) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *StatementTransaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StatementTransaction) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *StatementTransaction) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *StatementTransaction) GetPerformTime() int64 {
	if x != nil {
		return x.PerformTime
	}
	return 0
}

func (x *StatementTransaction) GetCancelTime() int64 {
	if x != nil {
		return x.CancelTime
	}
	return 0
}

func (x *StatementTransaction) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *StatementTransaction) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StatementTransaction) GetReason() int32 {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return 0
}

func (x *StatementTransaction) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

type GetStatementResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Transactions  []*StatementTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementResponse) Reset() {
	*x = GetStatementResponse{}
	mi := &file_payment_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementResponse) ProtoMessage() {}

func (x *GetStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementResponse.ProtoReflect.Descriptor instead.
func (*GetStatementResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{27}
}

func (x *GetStatementResponse) GetTransactions() []*StatementTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\x06school\x1a\x1bgoogle/protobuf/empty.proto\"\xcb\x01\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmonthly_fee\x18\x03 \x01(\x03R\n" +
	"monthlyFee\x12\x19\n" +
	"\bmfo_code\x18\x04 \x01(\tR\amfoCode\x12%\n" +
	"\x0eaccount_number\x18\x05 \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\btopic_id\x18\a \x01(\x03R\atopicId\"\xce\x02\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\tR\bbranchId\x12\x1f\n" +
	"\vparent_name\x18\x04 \x01(\tR\n" +
	"parentName\x12)\n" +
	"\x10discount_percent\x18\x05 \x01(\x01R\x0fdiscountPercent\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x03R\abalance\x12\x1b\n" +
	"\tfull_name\x18\a \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"group_name\x18\b \x01(\tR\tgroupName\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12'\n" +
	"\x0fcontract_number\x18\n" +
	" \x01(\tR\x0econtractNumber\x12\x16\n" +
	"\x06status\x18\v \x01(\bR\x06status\"\x1d\n" +
	"\vByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x12ByAccountIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\r\n" +
	"\vListRequest\"\xc8\x01\n" +
	"\x13CreateBranchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmonthly_fee\x18\x02 \x01(\x03R\n" +
	"monthlyFee\x12\x19\n" +
	"\bmfo_code\x18\x03 \x01(\tR\amfoCode\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\btopic_id\x18\x06 \x01(\x03R\atopicId\"B\n" +
	"\x14ListBranchesResponse\x12*\n" +
	"\bbranches\x18\x01 \x03(\v2\x0e.school.BranchR\bbranches\"\x99\x02\n" +
	"\x14CreateStudentRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12\x1f\n" +
	"\vparent_name\x18\x03 \x01(\tR\n" +
	"parentName\x12)\n" +
	"\x10discount_percent\x18\x04 \x01(\x01R\x0fdiscountPercent\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x06 \x01(\tR\tgroupName\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12'\n" +
	"\x0fcontract_number\x18\b \x01(\tR\x0econtractNumber\"C\n" +
	"\x14ListStudentsResponse\x12+\n" +
	"\bstudents\x18\x01 \x03(\v2\x0f.school.StudentR\bstudents\"V\n" +
	"\x1aCreateStudentsBatchRequest\x128\n" +
	"\bstudents\x18\x01 \x03(\v2\x1c.school.CreateStudentRequestR\bstudents\"J\n" +
	"\x1bCreateStudentsBatchResponse\x12+\n" +
	"\bstudents\x18\x01 \x03(\v2\x0f.school.StudentR\bstudents\"I\n" +
	"\x1aUpdateStudentsBatchRequest\x12+\n" +
	"\bstudents\x18\x01 \x03(\v2\x0f.school.StudentR\bstudents\"=\n" +
	"\x1aDeleteStudentsBatchRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"\x19\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x1eCheckPerformTransactionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12)\n" +
	"\aaccount\x18\x02 \x01(\v2\x0f.school.AccountR\aaccount\"\x9e\x02\n" +
	"\x15StudentAdditionalInfo\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x1f\n" +
	"\vparent_name\x18\x02 \x01(\tR\n" +
	"parentName\x12\x1f\n" +
	"\vbranch_name\x18\x03 \x01(\tR\n" +
	"branchName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12!\n" +
	"\fgroup_number\x18\x05 \x01(\tR\vgroupNumber\x12\"\n" +
	"\ramount_to_pay\x18\x06 \x01(\x03R\vamountToPay\x12\x19\n" +
	"\bmfo_code\x18\a \x01(\tR\amfoCode\x12%\n" +
	"\x0eaccount_number\x18\b \x01(\tR\raccountNumber\"v\n" +
	"\x1fCheckPerformTransactionResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12=\n" +
	"\n" +
	"additional\x18\x02 \x01(\v2\x1d.school.StudentAdditionalInfoR\n" +
	"additional\"\x81\x01\n" +
	"\x18CreateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12)\n" +
	"\aaccount\x18\x04 \x01(\v2\x0f.school.AccountR\aaccount\"2\n" +
	"\bReceiver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xa4\x01\n" +
	"\x19CreateTransactionResponse\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\x03R\n" +
	"createTime\x12 \n" +
	"\vtransaction\x18\x02 \x01(\tR\vtransaction\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\x12.\n" +
	"\treceivers\x18\x04 \x03(\v2\x10.school.ReceiverR\treceivers\"$\n" +
	"\x12TransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x1aPerformTransactionResponse\x12 \n" +
	"\vtransaction\x18\x01 \x01(\tR\vtransaction\x12!\n" +
	"\fperform_time\x18\x02 \x01(\x03R\vperformTime\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"B\n" +
	"\x18CancelTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\x05R\x06reason\"t\n" +
	"\x19CancelTransactionResponse\x12 \n" +
	"\vtransaction\x18\x01 \x01(\tR\vtransaction\x12\x1f\n" +
	"\vcancel_time\x18\x02 \x01(\x03R\n" +
	"cancelTime\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"\xdf\x01\n" +
	"\x18CheckTransactionResponse\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\x03R\n" +
	"createTime\x12!\n" +
	"\fperform_time\x18\x02 \x01(\x03R\vperformTime\x12\x1f\n" +
	"\vcancel_time\x18\x03 \x01(\x03R\n" +
	"cancelTime\x12 \n" +
	"\vtransaction\x18\x04 \x01(\tR\vtransaction\x12\x14\n" +
	"\x05state\x18\x05 \x01(\x05R\x05state\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\x05H\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"9\n" +
	"\x13GetStatementRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\"\xf2\x02\n" +
	"\x14StatementTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12)\n" +
	"\aaccount\x18\x04 \x01(\v2\x0f.school.AccountR\aaccount\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\x12!\n" +
	"\fperform_time\x18\x06 \x01(\x03R\vperformTime\x12\x1f\n" +
	"\vcancel_time\x18\a \x01(\x03R\n" +
	"cancelTime\x12 \n" +
	"\vtransaction\x18\b \x01(\tR\vtransaction\x12\x14\n" +
	"\x05state\x18\t \x01(\x05R\x05state\x12\x1b\n" +
	"\x06reason\x18\n" +
	" \x01(\x05H\x00R\x06reason\x88\x01\x01\x12.\n" +
	"\treceivers\x18\v \x03(\v2\x10.school.ReceiverR\treceiversB\t\n" +
	"\a_reason\"X\n" +
	"\x14GetStatementResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.school.StatementTransactionR\ftransactions2\xa3\x04\n" +
	"\x0ePaymentService\x12j\n" +
	"\x17CheckPerformTransaction\x12&.school.CheckPerformTransactionRequest\x1a'.school.CheckPerformTransactionResponse\x12X\n" +
	"\x11CreateTransaction\x12 .school.CreateTransactionRequest\x1a!.school.CreateTransactionResponse\x12T\n" +
	"\x12PerformTransaction\x12\x1a.school.TransactionRequest\x1a\".school.PerformTransactionResponse\x12X\n" +
	"\x11CancelTransaction\x12 .school.CancelTransactionRequest\x1a!.school.CancelTransactionResponse\x12P\n" +
	"\x10CheckTransaction\x12\x1a.school.TransactionRequest\x1a .school.CheckTransactionResponse\x12I\n" +
	"\fGetStatement\x12\x1b.school.GetStatementRequest\x1a\x1c.school.GetStatementResponse2\x87\a\n" +
	"\x11ManagementService\x12;\n" +
	"\fCreateBranch\x12\x1b.school.CreateBranchRequest\x1a\x0e.school.Branch\x120\n" +
	"\tGetBranch\x12\x13.school.ByIdRequest\x1a\x0e.school.Branch\x12D\n" +
	"\fListBranches\x12\x16.google.protobuf.Empty\x1a\x1c.school.ListBranchesResponse\x12.\n" +
	"\fUpdateBranch\x12\x0e.school.Branch\x1a\x0e.school.Branch\x12;\n" +
	"\fDeleteBranch\x12\x13.school.ByIdRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\rCreateStudent\x12\x1c.school.CreateStudentRequest\x1a\x0f.school.Student\x12D\n" +
	"\x15GetStudentByAccountId\x12\x1a.school.ByAccountIdRequest\x1a\x0f.school.Student\x12A\n" +
	"\fListStudents\x12\x13.school.ListRequest\x1a\x1c.school.ListStudentsResponse\x121\n" +
	"\rUpdateStudent\x12\x0f.school.Student\x1a\x0f.school.Student\x12N\n" +
	"\x18DeleteStudentByAccountId\x12\x1a.school.ByAccountIdRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x13CreateStudentsBatch\x12\".school.CreateStudentsBatchRequest\x1a#.school.CreateStudentsBatchResponse\x12Q\n" +
	"\x13UpdateStudentsBatch\x12\".school.UpdateStudentsBatchRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x13DeleteStudentsBatch\x12\".school.DeleteStudentsBatchRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1capi-gateway/genproto/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_payment_proto_goTypes = []any{
	(*Branch)(nil),                          // 0: school.Branch
	(*Student)(nil),                         // 1: school.Student
	(*ByIdRequest)(nil),                     // 2: school.ByIdRequest
	(*ByAccountIdRequest)(nil),              // 3: school.ByAccountIdRequest
	(*ListRequest)(nil),                     // 4: school.ListRequest
	(*CreateBranchRequest)(nil),             // 5: school.CreateBranchRequest
	(*ListBranchesResponse)(nil),            // 6: school.ListBranchesResponse
	(*CreateStudentRequest)(nil),            // 7: school.CreateStudentRequest
	(*ListStudentsResponse)(nil),            // 8: school.ListStudentsResponse
	(*CreateStudentsBatchRequest)(nil),      // 9: school.CreateStudentsBatchRequest
	(*CreateStudentsBatchResponse)(nil),     // 10: school.CreateStudentsBatchResponse
	(*UpdateStudentsBatchRequest)(nil),      // 11: school.UpdateStudentsBatchRequest
	(*DeleteStudentsBatchRequest)(nil),      // 12: school.DeleteStudentsBatchRequest
	(*Account)(nil),                         // 13: school.Account
	(*CheckPerformTransactionRequest)(nil),  // 14: school.CheckPerformTransactionRequest
	(*StudentAdditionalInfo)(nil),           // 15: school.StudentAdditionalInfo
	(*CheckPerformTransactionResponse)(nil), // 16: school.CheckPerformTransactionResponse
	(*CreateTransactionRequest)(nil),        // 17: school.CreateTransactionRequest
	(*Receiver)(nil),                        // 18: school.Receiver
	(*CreateTransactionResponse)(nil),       // 19: school.CreateTransactionResponse
	(*TransactionRequest)(nil),              // 20: school.TransactionRequest
	(*PerformTransactionResponse)(nil),      // 21: school.PerformTransactionResponse
	(*CancelTransactionRequest)(nil),        // 22: school.CancelTransactionRequest
	(*CancelTransactionResponse)(nil),       // 23: school.CancelTransactionResponse
	(*CheckTransactionResponse)(nil),        // 24: school.CheckTransactionResponse
	(*GetStatementRequest)(nil),             // 25: school.GetStatementRequest
	(*StatementTransaction)(nil),            // 26: school.StatementTransaction
	(*GetStatementResponse)(nil),            // 27: school.GetStatementResponse
	(*emptypb.Empty)(nil),                   // 28: google.protobuf.Empty
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: school.ListBranchesResponse.branches:type_name -> school.Branch
	1,  // 1: school.ListStudentsResponse.students:type_name -> school.Student
	7,  // 2: school.CreateStudentsBatchRequest.students:type_name -> school.CreateStudentRequest
	1,  // 3: school.CreateStudentsBatchResponse.students:type_name -> school.Student
	1,  // 4: school.UpdateStudentsBatchRequest.students:type_name -> school.Student
	13, // 5: school.CheckPerformTransactionRequest.account:type_name -> school.Account
	15, // 6: school.CheckPerformTransactionResponse.additional:type_name -> school.StudentAdditionalInfo
	13, // 7: school.CreateTransactionRequest.account:type_name -> school.Account
	18, // 8: school.CreateTransactionResponse.receivers:type_name -> school.Receiver
	13, // 9: school.StatementTransaction.account:type_name -> school.Account
	18, // 10: school.StatementTransaction.receivers:type_name -> school.Receiver
	26, // 11: school.GetStatementResponse.transactions:type_name -> school.StatementTransaction
	14, // 12: school.PaymentService.CheckPerformTransaction:input_type -> school.CheckPerformTransactionRequest
	17, // 13: school.PaymentService.CreateTransaction:input_type -> school.CreateTransactionRequest
	20, // 14: school.PaymentService.PerformTransaction:input_type -> school.TransactionRequest
	22, // 15: school.PaymentService.CancelTransaction:input_type -> school.CancelTransactionRequest
	20, // 16: school.PaymentService.CheckTransaction:input_type -> school.TransactionRequest
	25, // 17: school.PaymentService.GetStatement:input_type -> school.GetStatementRequest
	5,  // 18: school.ManagementService.CreateBranch:input_type -> school.CreateBranchRequest
	2,  // 19: school.ManagementService.GetBranch:input_type -> school.ByIdRequest
	28, // 20: school.ManagementService.ListBranches:input_type -> google.protobuf.Empty
	0,  // 21: school.ManagementService.UpdateBranch:input_type -> school.Branch
	2,  // 22: school.ManagementService.DeleteBranch:input_type -> school.ByIdRequest
	7,  // 23: school.ManagementService.CreateStudent:input_type -> school.CreateStudentRequest
	3,  // 24: school.ManagementService.GetStudentByAccountId:input_type -> school.ByAccountIdRequest
	4,  // 25: school.ManagementService.ListStudents:input_type -> school.ListRequest
	1,  // 26: school.ManagementService.UpdateStudent:input_type -> school.Student
	3,  // 27: school.ManagementService.DeleteStudentByAccountId:input_type -> school.ByAccountIdRequest
	9,  // 28: school.ManagementService.CreateStudentsBatch:input_type -> school.CreateStudentsBatchRequest
	11, // 29: school.ManagementService.UpdateStudentsBatch:input_type -> school.UpdateStudentsBatchRequest
	12, // 30: school.ManagementService.DeleteStudentsBatch:input_type -> school.DeleteStudentsBatchRequest
	16, // 31: school.PaymentService.CheckPerformTransaction:output_type -> school.CheckPerformTransactionResponse
	19, // 32: school.PaymentService.CreateTransaction:output_type -> school.CreateTransactionResponse
	21, // 33: school.PaymentService.PerformTransaction:output_type -> school.PerformTransactionResponse
	23, // 34: school.PaymentService.CancelTransaction:output_type -> school.CancelTransactionResponse
	24, // 35: school.PaymentService.CheckTransaction:output_type -> school.CheckTransactionResponse
	27, // 36: school.PaymentService.GetStatement:output_type -> school.GetStatementResponse
	0,  // 37: school.ManagementService.CreateBranch:output_type -> school.Branch
	0,  // 38: school.ManagementService.GetBranch:output_type -> school.Branch
	6,  // 39: school.ManagementService.ListBranches:output_type -> school.ListBranchesResponse
	0,  // 40: school.ManagementService.UpdateBranch:output_type -> school.Branch
	28, // 41: school.ManagementService.DeleteBranch:output_type -> google.protobuf.Empty
	1,  // 42: school.ManagementService.CreateStudent:output_type -> school.Student
	1,  // 43: school.ManagementService.GetStudentByAccountId:output_type -> school.Student
	8,  // 44: school.ManagementService.ListStudents:output_type -> school.ListStudentsResponse
	1,  // 45: school.ManagementService.UpdateStudent:output_type -> school.Student
	28, // 46: school.ManagementService.DeleteStudentByAccountId:output_type -> google.protobuf.Empty
	10, // 47: school.ManagementService.CreateStudentsBatch:output_type -> school.CreateStudentsBatchResponse
	28, // 48: school.ManagementService.UpdateStudentsBatch:output_type -> google.protobuf.Empty
	28, // 49: school.ManagementService.DeleteStudentsBatch:output_type -> google.protobuf.Empty
	31, // [31:50] is the sub-list for method output_type
	12, // [12:31] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_payment_proto_msgTypes[24].OneofWrappers = []any{}
	file_payment_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
