// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CheckPerformTransaction_FullMethodName = "/school.PaymentService/CheckPerformTransaction"
	PaymentService_CreateTransaction_FullMethodName       = "/school.PaymentService/CreateTransaction"
	PaymentService_PerformTransaction_FullMethodName      = "/school.PaymentService/PerformTransaction"
	PaymentService_CancelTransaction_FullMethodName       = "/school.PaymentService/CancelTransaction"
	PaymentService_CheckTransaction_FullMethodName        = "/school.PaymentService/CheckTransaction"
	PaymentService_GetStatement_FullMethodName            = "/school.PaymentService/GetStatement"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CheckPerformTransaction(ctx context.Context, in *CheckPerformTransactionRequest, opts ...grpc.CallOption) (*CheckPerformTransactionResponse, error)
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	PerformTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*PerformTransactionResponse, error)
	CancelTransaction(ctx context.Context, in *CancelTransactionRequest, opts ...grpc.CallOption) (*CancelTransactionResponse, error)
	CheckTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error)
	GetStatement(ctx context.Context, in *GetStatementRequest, opts ...grpc.CallOption) (*GetStatementResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CheckPerformTransaction(ctx context.Context, in *CheckPerformTransactionRequest, opts ...grpc.CallOption) (*CheckPerformTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPerformTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_CheckPerformTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) PerformTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*PerformTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_PerformTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelTransaction(ctx context.Context, in *CancelTransactionRequest, opts ...grpc.CallOption) (*CancelTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_CancelTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CheckTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetStatement(ctx context.Context, in *GetStatementRequest, opts ...grpc.CallOption) (*GetStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatementResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CheckPerformTransaction(context.Context, *CheckPerformTransactionRequest) (*CheckPerformTransactionResponse, error)
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	PerformTransaction(context.Context, *TransactionRequest) (*PerformTransactionResponse, error)
	CancelTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error)
	CheckTransaction(context.Context, *TransactionRequest) (*CheckTransactionResponse, error)
	GetStatement(context.Context, *GetStatementRequest) (*GetStatementResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CheckPerformTransaction(context.Context, *CheckPerformTransactionRequest) (*CheckPerformTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPerformTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) PerformTransaction(context.Context, *TransactionRequest) (*PerformTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PerformTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) CancelTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) CheckTransaction(context.Context, *TransactionRequest) (*CheckTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) GetStatement(context.Context, *GetStatementRequest) (*GetStatementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatement not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CheckPerformTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPerformTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CheckPerformTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CheckPerformTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CheckPerformTransaction(ctx, req.(*CheckPerformTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_PerformTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PerformTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_PerformTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PerformTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CancelTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelTransaction(ctx, req.(*CancelTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CheckTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetStatement(ctx, req.(*GetStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "school.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPerformTransaction",
			Handler:    _PaymentService_CheckPerformTransaction_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _PaymentService_CreateTransaction_Handler,
		},
		{
			MethodName: "PerformTransaction",
			Handler:    _PaymentService_PerformTransaction_Handler,
		},
		{
			MethodName: "CancelTransaction",
			Handler:    _PaymentService_CancelTransaction_Handler,
		},
		{
			MethodName: "CheckTransaction",
			Handler:    _PaymentService_CheckTransaction_Handler,
		},
		{
			MethodName: "GetStatement",
			Handler:    _PaymentService_GetStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}

const (
	ManagementService_CreateBranch_FullMethodName             = "/school.ManagementService/CreateBranch"
	ManagementService_GetBranch_FullMethodName                = "/school.ManagementService/GetBranch"
	ManagementService_ListBranches_FullMethodName             = "/school.ManagementService/ListBranches"
	ManagementService_UpdateBranch_FullMethodName             = "/school.ManagementService/UpdateBranch"
	ManagementService_DeleteBranch_FullMethodName             = "/school.ManagementService/DeleteBranch"
	ManagementService_CreateStudent_FullMethodName            = "/school.ManagementService/CreateStudent"
	ManagementService_GetStudentByAccountId_FullMethodName    = "/school.ManagementService/GetStudentByAccountId"
	ManagementService_ListStudents_FullMethodName             = "/school.ManagementService/ListStudents"
	ManagementService_UpdateStudent_FullMethodName            = "/school.ManagementService/UpdateStudent"
	ManagementService_DeleteStudentByAccountId_FullMethodName = "/school.ManagementService/DeleteStudentByAccountId"
	ManagementService_CreateStudentsBatch_FullMethodName      = "/school.ManagementService/CreateStudentsBatch"
	ManagementService_UpdateStudentsBatch_FullMethodName      = "/school.ManagementService/UpdateStudentsBatch"
	ManagementService_DeleteStudentsBatch_FullMethodName      = "/school.ManagementService/DeleteStudentsBatch"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagementServiceClient interface {
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*Branch, error)
	GetBranch(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Branch, error)
	ListBranches(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBranchesResponse, error)
	UpdateBranch(ctx context.Context, in *Branch, opts ...grpc.CallOption) (*Branch, error)
	DeleteBranch(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*Student, error)
	GetStudentByAccountId(ctx context.Context, in *ByAccountIdRequest, opts ...grpc.CallOption) (*Student, error)
	ListStudents(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error)
	UpdateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error)
	DeleteStudentByAccountId(ctx context.Context, in *ByAccountIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateStudentsBatch(ctx context.Context, in *CreateStudentsBatchRequest, opts ...grpc.CallOption) (*CreateStudentsBatchResponse, error)
	UpdateStudentsBatch(ctx context.Context, in *UpdateStudentsBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteStudentsBatch(ctx context.Context, in *DeleteStudentsBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*Branch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Branch)
	err := c.cc.Invoke(ctx, ManagementService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetBranch(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*Branch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Branch)
	err := c.cc.Invoke(ctx, ManagementService_GetBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListBranches(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateBranch(ctx context.Context, in *Branch, opts ...grpc.CallOption) (*Branch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Branch)
	err := c.cc.Invoke(ctx, ManagementService_UpdateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteBranch(ctx context.Context, in *ByIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_DeleteBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*Student, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Student)
	err := c.cc.Invoke(ctx, ManagementService_CreateStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetStudentByAccountId(ctx context.Context, in *ByAccountIdRequest, opts ...grpc.CallOption) (*Student, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Student)
	err := c.cc.Invoke(ctx, ManagementService_GetStudentByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListStudents(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListStudentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStudentsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Student)
	err := c.cc.Invoke(ctx, ManagementService_UpdateStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteStudentByAccountId(ctx context.Context, in *ByAccountIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_DeleteStudentByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateStudentsBatch(ctx context.Context, in *CreateStudentsBatchRequest, opts ...grpc.CallOption) (*CreateStudentsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStudentsBatchResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateStudentsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateStudentsBatch(ctx context.Context, in *UpdateStudentsBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_UpdateStudentsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteStudentsBatch(ctx context.Context, in *DeleteStudentsBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ManagementService_DeleteStudentsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
type ManagementServiceServer interface {
	CreateBranch(context.Context, *CreateBranchRequest) (*Branch, error)
	GetBranch(context.Context, *ByIdRequest) (*Branch, error)
	ListBranches(context.Context, *emptypb.Empty) (*ListBranchesResponse, error)
	UpdateBranch(context.Context, *Branch) (*Branch, error)
	DeleteBranch(context.Context, *ByIdRequest) (*emptypb.Empty, error)
	CreateStudent(context.Context, *CreateStudentRequest) (*Student, error)
	GetStudentByAccountId(context.Context, *ByAccountIdRequest) (*Student, error)
	ListStudents(context.Context, *ListRequest) (*ListStudentsResponse, error)
	UpdateStudent(context.Context, *Student) (*Student, error)
	DeleteStudentByAccountId(context.Context, *ByAccountIdRequest) (*emptypb.Empty, error)
	CreateStudentsBatch(context.Context, *CreateStudentsBatchRequest) (*CreateStudentsBatchResponse, error)
	UpdateStudentsBatch(context.Context, *UpdateStudentsBatchRequest) (*emptypb.Empty, error)
	DeleteStudentsBatch(context.Context, *DeleteStudentsBatchRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*Branch, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedManagementServiceServer) GetBranch(context.Context, *ByIdRequest) (*Branch, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranch not implemented")
}
func (UnimplementedManagementServiceServer) ListBranches(context.Context, *emptypb.Empty) (*ListBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedManagementServiceServer) UpdateBranch(context.Context, *Branch) (*Branch, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBranch not implemented")
}
func (UnimplementedManagementServiceServer) DeleteBranch(context.Context, *ByIdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBranch not implemented")
}
func (UnimplementedManagementServiceServer) CreateStudent(context.Context, *CreateStudentRequest) (*Student, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStudent not implemented")
}
func (UnimplementedManagementServiceServer) GetStudentByAccountId(context.Context, *ByAccountIdRequest) (*Student, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentByAccountId not implemented")
}
func (UnimplementedManagementServiceServer) ListStudents(context.Context, *ListRequest) (*ListStudentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStudents not implemented")
}
func (UnimplementedManagementServiceServer) UpdateStudent(context.Context, *Student) (*Student, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStudent not implemented")
}
func (UnimplementedManagementServiceServer) DeleteStudentByAccountId(context.Context, *ByAccountIdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStudentByAccountId not implemented")
}
func (UnimplementedManagementServiceServer) CreateStudentsBatch(context.Context, *CreateStudentsBatchRequest) (*CreateStudentsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStudentsBatch not implemented")
}
func (UnimplementedManagementServiceServer) UpdateStudentsBatch(context.Context, *UpdateStudentsBatchRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStudentsBatch not implemented")
}
func (UnimplementedManagementServiceServer) DeleteStudentsBatch(context.Context, *DeleteStudentsBatchRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStudentsBatch not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetBranch(ctx, req.(*ByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListBranches(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Branch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateBranch(ctx, req.(*Branch))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeleteBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteBranch(ctx, req.(*ByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateStudent(ctx, req.(*CreateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetStudentByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetStudentByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetStudentByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetStudentByAccountId(ctx, req.(*ByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListStudents(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteStudentByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteStudentByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeleteStudentByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteStudentByAccountId(ctx, req.(*ByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateStudentsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateStudentsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateStudentsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateStudentsBatch(ctx, req.(*CreateStudentsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateStudentsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateStudentsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateStudentsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateStudentsBatch(ctx, req.(*UpdateStudentsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteStudentsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteStudentsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeleteStudentsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteStudentsBatch(ctx, req.(*DeleteStudentsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "school.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBranch",
			Handler:    _ManagementService_CreateBranch_Handler,
		},
		{
			MethodName: "GetBranch",
			Handler:    _ManagementService_GetBranch_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _ManagementService_ListBranches_Handler,
		},
		{
			MethodName: "UpdateBranch",
			Handler:    _ManagementService_UpdateBranch_Handler,
		},
		{
			MethodName: "DeleteBranch",
			Handler:    _ManagementService_DeleteBranch_Handler,
		},
		{
			MethodName: "CreateStudent",
			Handler:    _ManagementService_CreateStudent_Handler,
		},
		{
			MethodName: "GetStudentByAccountId",
			Handler:    _ManagementService_GetStudentByAccountId_Handler,
		},
		{
			MethodName: "ListStudents",
			Handler:    _ManagementService_ListStudents_Handler,
		},
		{
			MethodName: "UpdateStudent",
			Handler:    _ManagementService_UpdateStudent_Handler,
		},
		{
			MethodName: "DeleteStudentByAccountId",
			Handler:    _ManagementService_DeleteStudentByAccountId_Handler,
		},
		{
			MethodName: "CreateStudentsBatch",
			Handler:    _ManagementService_CreateStudentsBatch_Handler,
		},
		{
			MethodName: "UpdateStudentsBatch",
			Handler:    _ManagementService_UpdateStudentsBatch_Handler,
		},
		{
			MethodName: "DeleteStudentsBatch",
			Handler:    _ManagementService_DeleteStudentsBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
